const fs=require('fs'),{execSync}=require('child_process');if(!fs.existsSync('./package.json')){fs.writeFileSync('./package.json',JSON.stringify({name:"elite-bot",version:"1.0.0",main:"index.js",dependencies:{"@whiskeysockets/baileys":"^6.7.9","@hapi/boom":"^10.0.1",pino:"^9.0.0"}},null,2))}try{require('@whiskeysockets/baileys');require('@hapi/boom')}catch(e){console.log('⏳ Installing...');execSync('npm install',{stdio:'inherit'})}
const{default:makeWASocket,useMultiFileAuthState,DisconnectReason}=require('@whiskeysockets/baileys'),{Boom}=require('@hapi/boom'),OWNER="213561055648@s.whatsapp.net",BOT_NUM="213555982437",dbFile='./database.json',VALID_CMDS=['تشغيل','ايقاف','تسجيل','نقاطي','بنك','رهان','تحويل','نخبة','مطور'];
function loadDB(){if(!fs.existsSync(dbFile))fs.writeFileSync(dbFile,'{}');try{return JSON.parse(fs.readFileSync(dbFile,'utf-8'))}catch{return{}}}function saveDB(d){fs.writeFileSync(dbFile,JSON.stringify(d,null,2))}function checkAcc(i){let db=loadDB();if(!db[i]){db[i]={name:"غير مسجل",points:1000,weekly:0,bank:0,buys:0,joined:new Date().toLocaleDateString('ar-EG'),betCount:0};saveDB(db)}return db[i]}
async function startBot(){const{state,saveCreds}=await useMultiFileAuthState('auth_info_baileys'),sock=makeWASocket({auth:state,printQRInTerminal:false,logger:require('pino')({level:'silent'})});if(!sock.authState.creds.registered){setTimeout(async()=>{try{let c=await sock.requestPairingCode(BOT_NUM);console.log(`\n🔥 ELITE BOT CODE: 【 ${c} 】\n`)}catch{}},7000)}sock.ev.on('creds.update',saveCreds);sock.ev.on('connection.update',u=>{if(u.connection==='close'){if((u.lastDisconnect.error instanceof Boom)?u.lastDisconnect.error.output.statusCode!==DisconnectReason.loggedOut:true)startBot()}else if(u.connection==='open')console.log('🚀 Connected!')});
sock.ev.on('messages.upsert',async m=>{const msg=m.messages[0];if(!msg.message||msg.key.fromMe)return;const from=msg.key.remoteJid,sender=msg.key.participant||from,body=msg.message.conversation||msg.message.extendedTextMessage?.text||"";if(!body.startsWith('.'))return;const args=body.slice(1).trim().split(/ +/),command=args.shift().toLowerCase();let db=loadDB(),groupActive=db[`act_${from}`]!==false,isAdmin=false;if(from.endsWith('@g.us')){try{const meta=await sock.groupMetadata(from);isAdmin=meta.participants.find(p=>p.id===sender)?.admin!==null}catch{}}const isOwner=sender===OWNER,isElite=db[`elite_user` ]===sender;
if(command==='نخبة'){if(db[`elite_user`]){let e=db[`elite_user`],t=`@${e.split('@')[0]}`;return sock.sendMessage(from,{text:`عمك ${t} هو النخبة الوحيد فالبوت يلا هش 🤫🔥`,mentions:[e]},{quoted:msg})}db[`elite_user`]=sender;saveDB(db);return sock.sendMessage(from,{text:`👑 *أصبحت الآن نخبة البوت وملك الصلاحيات!*`},{quoted:msg})}if(command==='مطور')return sock.sendMessage(from,{text:"👑 *مطور البوت:* +213567055648\n\n💪 🇩🇿 *تحيا الجزائر!*"},{quoted:msg});if(!VALID_CMDS.includes(command)){if(!groupActive&&!isOwner&&!isElite)return;return sock.sendMessage(from,{text:`❌ الأمر غير موجود، وشكراً.`},{quoted:msg})}
if(command==='تشغيل'){if(!isAdmin&&!isOwner&&!isElite)return;db[`act_${from}`]=true;saveDB(db);return sock.sendMessage(from,{text:"⚡ *تم التفعيل!*"},{quoted:msg})}if(command==='ايقاف'){if(!isAdmin&&!isOwner&&!isElite)return;db[`act_${from}`]=false;saveDB(db);return sock.sendMessage(from,{text:"🛑 *تم الإيقاف!*"},{quoted:msg})}if(!groupActive&&!isOwner&&!isElite)return;
if(command==='تسجيل'){let n=args.join(" ");if(!n)return sock.sendMessage(from,{text:"💡 مثال: `.تسجيل أحمد`"},{quoted:msg});checkAcc(sender);db=loadDB();db[sender].name=n;saveDB(db);return sock.sendMessage(from,{text:`تم تسجيل: *${n}* @${sender.split('@')[0]}\nمرحبا بك اتمنى تستمتع فالبوت مع اصحابك`,mentions:[sender]},{quoted:msg})}
if(command==='نقاطي'){let u=checkAcc(sender);return sock.sendMessage(from,{text:`╭─「 👤 *بطاقتك* 」\n│ اللقب: *${u.name}*\n│ 📱 @${sender.split('@')[0]}\n│ 💰 النقاط الكلية: *${u.points}*\n│ 📅 هذا الأسبوع: *${u.weekly}*\n│ 🛒 مشتريات: *${u.buys}*\n│ 📆 انضم: *${u.joined}*\n╰──────────────────`,mentions:[sender]},{quoted:msg})}
if(command==='بنك'){let s=args[0]?.toLowerCase(),amt=parseInt(args[1]),u=checkAcc(sender);if(!s)return sock.sendMessage(from,{text:`╭─「 🏦 *بنكك* 」\n│ 💰 نقاطك: *${u.points}*\n│ 🏦 رصيد البنك: *${u.bank}*\n│ 📌 الإيداع: *.بنك ايداع <مبلغ>*\n│ 📌 السحب: *.بنك سحب <مبلغ>*\n│ ⚠️ الرسوم: *10%*\n╰──────────────────`},{quoted:msg});db=loadDB();if(s==='ايداع'){if(isNaN(amt)||amt<=0||u.points<amt)return;let f=Math.floor(amt*0.1),net=amt-f;db[sender].points-=amt;db[sender].bank+=net;saveDB(db);return sock.sendMessage(from,{text:`✅ *تم الإيداع!*\n💸 المطلوب: ${amt}\n💳 الرسوم: ${f}\n🏦 تم إيداع: ${net}\n💰 نقاطك الآن: ${db[sender].points}\n🏦 البنك: ${db[sender].bank}`},{quoted:msg})}if(s==='سحب'){if(isNaN(amt)||amt<=0||u.bank<amt)return;db[sender].bank-=amt;db[sender].points+=amt;saveDB(db);return sock.sendMessage(from,{text:`تم السحب من البنك 🏦\nنقاطك الان: ${db[sender].points}\nرصيد البنك: ${db[sender].bank}`},{quoted:msg})}}
if(command==='رهان'){let amt=parseInt(args[0]);if(isNaN(amt)||amt<=0)return;let u=checkAcc(sender);if(u.points<amt)return;db=loadDB();let w=false;if(amt===1){db[sender].betCount+=1;w=Math.random()<0.5}else{w=db[sender].betCount>=3?Math.random()<0.9:Math.random()<0.5;db[sender].betCount=0}if(w){db[sender].points+=amt;db[sender].weekly+=amt;saveDB(db);return sock.sendMessage(from,{text:`🎰 *ربحت الرهان!* 🎉\n💰 المبلغ: ${amt}\n📈 +${amt} نقطة\n💼 رصيدك: ${db[sender].points}\n@${sender.split('@')[0]} استمر! 🍀`,mentions:[sender]},{quoted:msg})}else{db[sender].points-=amt;saveDB(db);return sock.sendMessage(from,{text:`💀 *خسرت الرهان!*\n💰 المبلغ: ${amt}\n💼 رصيدك: ${db[sender].points}\n@${sender.split('@')[0]} حظ أفضل 😅`,mentions:[sender]},{quoted:msg})}}
if(command==='تحويل'){let amt=parseInt(args[0]),rec=msg.message.extendedTextMessage?.contextInfo?.mentionedJid?.[0];if(!rec||isNaN(amt)||amt<=0)return;let u=checkAcc(sender);checkAcc(rec);db=loadDB();if(u.points<amt)return;db[sender].points-=amt;db[rec].points+=amt;db[rec].weekly+=amt;saveDB(db);return sock.sendMessage(from,{text:`✅ تم تحويل *${amt}* نقطة بنجاح.`},{quoted:msg})}});
}startBot();
